### ISSUE TITLE
So lets add some content!

### ISSUE THREAD

**Issue by budparr** [budparr/gohugo.io#13]
So I guess for the moment, @rdwatters, you and I are the "editorial team," which is fine until we get things defined and have a way of being. So, just throwing some stuff out there. I'm happy to do the legwork here, but thought you'd want to weigh in.

The posts I have there were just the trial balloons, but we need to consider whether or not to publish the full release notes, or a more friendly highlights post, pointing to the full post. 

I'm also thinking we could go ahead and write something up about Smashing Mag.

**Comment by rdwatters** [comment]
> you and I are the "editorial team,"

I love this! 

I'm booked until about 5:30 central but will add some thoughts on here this evening. Or are you thinking we go straight to the wiki? Both work for me. Thanks!

**Comment by rdwatters** [comment]
I've been thinking about our conversation yesterday re: content strategy and how we should scope the content in a new blog/news/tips/whatever section.

Since I've removed the "tutorials" section from the current site, how about the following content "buckets":

1. Release Notes (I think we can keep the full-length text here with perhaps a bit of editorial oversight to make the presentation more consistent)
2. Targeted tutorials. I think you and I can set up some basic editorial guidelines for the scope of what we would want from contributors. I've mentioned this on other threads, but I think it's better to go niche here rather than having every tutorial be an extended version of the Quick Starts. I have a draft of a tutorial on how to use Google Sheets with Hugo's dynamic data features and list.js for easy sorting, filtering that I think would be cool. Other than that, maybe scaffold as such
    * CM Problem
    * Why Hugo is a good solution for said problem (i.e., some best practices)
    * Walkthrough of solution
    * Next Steps (maybe CMS layer, hosting, etc, but this would be article-dependent)
3. ??? I was thinking something to the effect of articles extolling the general benefits of static OR real-world examples of how Hugo (e.g. Smashing).

I think the tough part will be getting contributors to regularly add articles. If this picks up steam, I have experience with large distributed authorship workflows, editorial calendars, etc, but that's putting the cart before the horse...

**Comment by budparr** [comment]
My only concern with full release notes is that they will also be published elsewhere (the main repo at a minimum, likely with the docs, no?), and so it's a duplication of effort and leaves at least a slight potential for versions to be different. Also, longer, more detailed posts cause some people to click away. I like the Jekyll model, where there's a release post, pointing to the full release notes, for the reasons above. No need to decide now, these are just thoughts.

**Comment by rdwatters** [comment]
> likely with the docs, no?

Honestly, I was thinking we could maybe get rid of even rework the current "News" section (https://hugodocs.info/news/). I'm not sure release notes need to live in docs if we are going to have a separate section for articles. See below...

> I like the Jekyll model, where there's a release post, pointing to the full release notes, for the reasons above. 

From what I can tell, almost all of the content for Jekyll is just annotated release notes. That is, putting the release notes in a more narrative, long-form format. Is this what you had in mind? 

Here's another popular "blog" (i.e., just narrative release notes). 

http://blog.getbootstrap.com/

That said, I think we both agree the releases notes need to live in *some* format in this new area. What do you think about the rest?

**Comment by budparr** [comment]
I guess the only important thing about the docs is that they are consistently published somewhere where they're consistent and easy to find (they're good for troubleshooting). My idea behind putting some version on the news site was to make sure there was always _something_ there. 

One should not assume too much when planning for an open source project, so I think setting out some ideas like you have is fine, actually good, in that there should be some constraints/categories, etc, as a barrier to keep quality high. I've done some editorial work before, and my one take away from working with contributors is that they need to know the game in advance, because it's easier to say no with your requirements than it is with their submitted piece, if that makes sense.

I think your ideas there are good - just don't put too much on your self. I think posting about some things you'd want to highlight from the docs would be good, and uniquely your perspective.

**Comment by rdwatters** [comment]
> because it's easier to say no with your requirements than it is with their submitted piece, if that makes sense.

Definitely. I think this applies to all editorial, publishing, and distributed authorship models. It saves time for everyone involved.

**Comment by budparr** [comment]
@rdwatters n.b. https://guides.18f.gov/content-guide/ we may be able to use this in whole. It's open-source.

**Comment by budparr** [comment]
that is, of course, if we want to :)

**Comment by rdwatters** [comment]
> that is, of course, if we want to :)

Hell yes. This is great, and I've written enough style guides in my time that I can cross it off my bucket list:) Plus, using a big-fun style guide like CMS is a PITA for contributors. 

We'll still need to flesh out submission guidelines under the assumption that I'll still need to do some editorial review as part of future PRs.
